Feature/actor top source switcher
Vizzuality/TRASE-frontend pull request #372
Opened 2017-05-04 13:45 UTC by pjosh

![switcher2](https://cloud.githubusercontent.com/assets/1432880/25706405/a0c42954-30e0-11e7-9f0e-12211f95c26c.gif)

2017-05-04 15:23 UTC, pjosh commented
@nerik @sorodrigo ready to review!

2017-05-04 15:26 UTC, pjosh commented
Fixes #328

2017-05-05 13:38 UTC, sorodrigo commented on scripts/pages/profile-actor.page.js
> +    switchers: Object.keys(data.top_sources).filter(key => key !== 'included_years')
This will cause problems in the future if we add more props to `top_sources`.

2017-05-05 13:43 UTC, sorodrigo commented on scripts/pages/profile-actor.page.js
> +              value: `${formatNumber(location.value)}<span>Tons</span>` }
Use `unit: 'Tons'` instead of `<span>Ton</span>`

2017-05-05 13:47 UTC, sorodrigo requested changes

2017-05-05 13:47 UTC, sorodrigo commented on scripts/templates/profiles/top-source-switcher.ejs
> +<span>Sustainability of <%= nodeName %> top source reggions in 2015:</span>
typo in `reggions`

2017-05-05 16:10 UTC, sorodrigo approved these changes

2017-05-05 16:10 UTC, sorodrigo commented
@pjosh @nerik I attacked the remaining details, please review my mods. I think it may be ready for merging ;)

2017-05-05 22:47 UTC, pjosh commented
nice @sorodrigo !! 👏 👏

2017-05-05 22:48 UTC, merged