homepage posts
Vizzuality/TRASE-frontend pull request #61
Opened 2016-10-24 17:22 UTC by andresgnlez

2016-10-25 13:05 UTC, nerik requested changes

2016-10-25 13:05 UTC, nerik commented on scripts/pages/index.page.js
> +  d3_json('homepage/posts.json', (err, data) => {
Why didn't you use fetch/whatwg-fetch + JSON.parse ? This will add an unnecessary dependency to D3 in the index bundle.

2016-10-25 13:06 UTC, nerik commented
Please fix that JSON thing, and also rename the commit please. Otherwise looks good 👍

2016-10-26 13:41 UTC, andresgnlez commented
This is a `v1.0` of the dynamic grid. There are still some features to implement like choosing the position of vertical posts (left/right) but they are not critical and can be done in the next days.

2016-10-26 16:52 UTC, merged