add select area on factsheets-page
Vizzuality/TRASE-frontend pull request #73
Opened 2016-10-31 12:34 UTC by hectoruch

Add:

![image](https://cloud.githubusercontent.com/assets/8074563/19854329/b125ed7c-9f6e-11e6-86d5-950529faad51.png)

2016-10-31 16:42 UTC, hectoruch commented
Add:

- Grid lines

Delete: 

- Tick lines on chart

Update:

- Colors, font size, font family and other styles

![image](https://cloud.githubusercontent.com/assets/8074563/19862626/6fc8c6f6-9f91-11e6-8184-50c944acdd7c.png)

2016-11-01 09:28 UTC, nerik requested changes

2016-11-01 09:28 UTC, nerik commented on package.json
> +    "d3-array": "^1.0.1",
There is no need to manually import all d3 modules, as the entry point in the `d3` module already has references to all d3 modules.

2016-11-01 09:28 UTC, nerik commented on scripts/components/tables/area-tables.js
> +  .style('font-size', '12px');
While it is technically possible to build tables in d3 I strongly advise against it. Let's just use good old html tables for this.
We have a templating engine in the project taht you can use, see example here for use with a table https://github.com/Vizzuality/TRASE-frontend/pull/77/commits/be5e9cab367e6a40c94498b579e3b16e6d0b5b2d

2016-11-02 10:13 UTC, hectoruch commented
Add styles for table:

![image](https://cloud.githubusercontent.com/assets/8074563/19924709/66169e14-a0ed-11e6-9946-ee83e3c2dba2.png)

2016-11-02 10:35 UTC, andresgnlez commented on package.json
> +    "d3-array": "^1.0.1",
Agree. Please remove all those dependencies and use d3 modules already installed in the project. If you need any help with this, let us know.

2016-11-02 11:50 UTC, andresgnlez commented on html/factsheets.ejs
You forgot about adding a `wrap` here

2016-11-02 11:51 UTC, andresgnlez commented on html/factsheets.ejs
Please, add `max-width` to the layout

2016-11-02 11:53 UTC, andresgnlez commented on scripts/components/graphs/area-stack.component.js
> +      height: 380//this.el.clientHeight
are we sure this is not going to change?

2016-11-02 11:54 UTC, andresgnlez commented on scripts/components/graphs/area-stack.component.js
> +        .style('stroke-width', 1); //or style directly with attributes or inline styles
Please, move styles to its styles file.

2016-11-02 12:25 UTC, hectoruch commented
Add icons on:

- Table 
![image](https://cloud.githubusercontent.com/assets/8074563/19928678/c6e7d8c2-a0ff-11e6-8f92-6fc95288e9ad.png)

- Select area

![image](https://cloud.githubusercontent.com/assets/8074563/19928687/cfc757b0-a0ff-11e6-9781-76e27970dfe5.png)

2016-11-02 12:34 UTC, andresgnlez commented on styles/components/factsheets/area-select.scss
> +          width: 16px;
Icon sizes are setted in `icons` styles file. If you need to positionate them or similar do it here.

2016-11-02 12:35 UTC, andresgnlez commented on styles/components/factsheets/area-select.scss
> +          margin-right: 4px;
Same here.

2016-11-02 12:41 UTC, andresgnlez commented on package.json
> -{
Restore this! :P

2016-11-02 14:15 UTC, agnlez commented on scripts/components/graphs/area-stack.component.js
> +        .style('stroke-width', 1); //or style directly with attributes or inline styles
Move this to its CSS file, please.

2016-11-02 16:49 UTC, agnlez commented on html/factsheets.ejs
> +      <div class="content wrap">
Don't use the `wrap` with something else, if you need another class or whatever, use another different element

2016-11-02 16:50 UTC, andresgnlez commented on styles/layouts/l-factsheets.scss
> +  // max-width: $max-width-grid;
Get rid of commented code.

2016-11-02 18:39 UTC, merged